version: '3.4'

services:
  mysql:
    image: mysql:8.0
    container_name: acme-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: acme_seguros
      MYSQL_USER: acme_user
      MYSQL_PASSWORD: acme_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - acme-network

  localstack:
    image: localstack/localstack:3.0
    container_name: acme-localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d/init-sqs.sh
      - ./.localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - acme-network

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: acme-wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - acme-network

volumes:
  mysql_data:
  localstack_data:

networks:
  acme-network:
    driver: bridge
