spring:
  application:
    name: acme-seguradora-solicitacoes

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:acme_seguros}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:acme_user}
    password: ${DB_PASSWORD:acme_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: false

aws:
  region: us-east-1
  accessKeyId: ${AWS_ACCESS_KEY_ID:test}
  secretKey: ${AWS_SECRET_ACCESS_KEY:test}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
    queue-url-prefix: ${AWS_SQS_QUEUE_URL_PREFIX:http://localhost:4566/000000000000/}

fraude:
  api:
    url: ${FRAUDE_API_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.acme.seguradora: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
